Update basic-workflow.yaml

diff --git a/.github/workflows/basic-workflow.yaml b/.github/workflows/basic-workflow.yaml
--- a/.github/workflows/basic-workflow.yaml
+++ b/.github/workflows/basic-workflow.yaml
@@ -8,4 +8,8 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: The Thing I've Done
-        run: echo "I've done a thing! Again!"
+        run: echo "I've done a thing!"
+      - name: An Error I made
+        run: |
+          echo "I've made an error!"
+          exit 1
